### ISSUE TITLE
Psi not install in Server [CLOSED]

### ISSUE THREAD

**Issue by Rumaruka** [Vazkii/Psi#117] opened 2016-03-04 14:52 UTC
Psi 18 and 19 build not install in Server 
http://pastebin.com/5D141tFn
Sorry, i think fix problem
CLOSED

**Comment by yrsegal** [comment] 2016-03-04 14:53
use java 8.

**Comment by yrsegal** [comment] 2016-03-04 14:54
@Vazkii, you probably should make an issue template which tells people to use java 8. https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by Wojbie** [comment] 2016-03-04 14:55
Duplicate of #115

**Comment by Rumaruka** [comment] 2016-03-04 15:22
Sorry , I first put the server.
How to use java8??

**Comment by yrsegal** [comment] 2016-03-04 21:17
You didn't actually close the issue...

**Closed** 2016-03-07 14:55 UTC
