### ISSUE TITLE
Start with 5000 mana

### ISSUE THREAD

**Issue by GoldenBlaze** [Vazkii/Psi#478] opened 2019-02-07 03:57 UTC
To start, I am running windows 10, 64 bit, with a Ryzen Processor.
I have no other mods installed other than Psi, JEI, and the required library.

I am having a strange issue. Every time I make a new world and attempt to start psi, I am started out with 5000 mana. I am also unable to use the programmer. I level up to level 1 when I make the psi dust. But I can't get any further. What is weirder is when I try an older version of psi I get the same problem. Granted I did only go back one version. But I have already spent multiple hours trying to figure out what's wrong.

Let me know if you need more info.

**Comment by yrsegal** [comment] 2019-02-07 03:58
You're using the latest version of Psi?

**Comment by GoldenBlaze** [comment] 2019-02-07 03:59
Indeed

**Comment by GoldenBlaze** [comment] 2019-02-07 03:59
Crap I meant to mention. I am using the twitch launcher.

**Comment by yrsegal** [comment] 2019-02-07 04:00
could you give a crash log? (hold f3 + c to manually crash your game)

**Comment by GoldenBlaze** [comment] 2019-02-07 04:00
Ok one sec

**Comment by GoldenBlaze** [comment] 2019-02-07 04:03
File or raw text?

**Comment by yrsegal** [comment] 2019-02-07 04:03
Upload it to a service like https://gist.github.com, https://hastebin.com, or https://pastebin.com, please.

**Comment by GoldenBlaze** [comment] 2019-02-07 04:04
https://hastebin.com/pazunitelu.rb

**Comment by yrsegal** [comment] 2019-02-07 04:06
Well, that's certainly the latest release... Odd. Could you upload a zipped world file for me to check out?

**Comment by GoldenBlaze** [comment] 2019-02-07 04:06
Sure give me another sec

**Comment by GoldenBlaze** [comment] 2019-02-07 04:08
[New World.zip](https://github.com/Vazkii/Psi/files/2839280/New.World.zip)

**Comment by GoldenBlaze** [comment] 2019-02-07 04:14
So are you experiencing the same thing? I made a quick video with OBS showing what's up if you want it.

**Comment by yrsegal** [comment] 2019-02-07 04:15
That would be great, thanks

**Comment by GoldenBlaze** [comment] 2019-02-07 04:15
ugh this thing doesn't take .mp4 I'll send it through mediafire.

**Comment by GoldenBlaze** [comment] 2019-02-07 04:17
https://www.mediafire.com/file/e7a6cw8z999mcq3/Psi_bs.mp4/file

**Comment by GoldenBlaze** [comment] 2019-02-07 04:21
I think at this point you have all the info that I have. I can't think of anything else that you might need. let me know though. I'll be on for like 30 more mins before I need to hit the sack.

**Comment by yrsegal** [comment] 2019-02-07 04:22
The 5000 psi issue is real, but you need to use the Psi keybind (which you have unbound) to progress.

**Comment by GoldenBlaze** [comment] 2019-02-07 04:23
No, I know. I unbound it when I tried to get the game to force a crash. I had never done it before and I didn't know how long I needed to hold it down so I unbound that key because I thought it was conflicting with the action.

**Comment by yrsegal** [comment] 2019-02-07 04:24
well, could you record the unable-to-progress issue?

**Comment by GoldenBlaze** [comment] 2019-02-07 04:24
Did you watch the video?

**Comment by GoldenBlaze** [comment] 2019-02-07 04:24
Or am I an idiot?

**Comment by yrsegal** [comment] 2019-02-07 04:24
I did. You never entered the Psi GUI, which requires the keybind.

**Comment by GoldenBlaze** [comment] 2019-02-07 04:25
Ok, I'm just an idiot. See I started using the mod because I wanted to learn it. I didn't hit learn. Which is my bad.

**Comment by yrsegal** [comment] 2019-02-07 04:26
My update branch now has a solution to this. It'll be merged when testing is done.

**Comment by GoldenBlaze** [comment] 2019-02-07 04:27
Yay!

**Comment by GoldenBlaze** [comment] 2019-02-07 04:29
You know. It kinda sucks when you try your best to not do something stupid and you end up making a really simple mistake.
Sorry for mislabling and being a numpty. Thanks for being prompt and helping me out.
:)

**Comment by yrsegal** [comment] 2019-02-07 13:46
So, it turns out that this is intended behavior, as of a few updates ago. Oops.

**Closed by yrsegal** 2019-02-07 13:46 UTC
Labels: invalid

**Comment by GoldenBlaze** [comment] 2019-02-07 14:03
Wait, does that mean it's supposed to be 5000? Like you are meant to start with 5000 mana?

**Comment by yrsegal** [comment] 2019-02-07 14:04
![Yep](https://cdn.discordapp.com/attachments/490653499273510942/543065683693666305/Screenshot_Discord_20190207-134846.png)

**Comment by GoldenBlaze** [comment] 2019-02-07 14:06
Oh... Ok... Did they just not like the leveling system or something? I'm confused as to why it was removed.

**Comment by Math321** [comment] 2019-02-09 02:12
You still have to unlock spell pieces, but your max Psi energy is always 5,000 now, @GoldenBlaze .
