### ISSUE TITLE
Crash with Psi circle spell bullet

### ISSUE THREAD

**Issue by TheGreatCatAdorer** [Vazkii/Psi#667] opened 2021-02-23 18:04 UTC
# Version Information
Forge version: 36.0.1
Psi version: 1.16-91

I created a circle spell to throw enemies 60 blocks into the air on an Ebony CAD.  When the spell was cast, the game crashed without a crashlog.

[latest.log](https://github.com/Vazkii/Psi/files/6030971/latest.log)

**Comment by TheGreatCatAdorer** [comment] 2021-02-23 18:26
It failed only when next to a Create moving contraption.

**Comment by TheGreatCatAdorer** [comment] 2021-02-23 18:41
Did it again with a different spell.

**Comment by TheGreatCatAdorer** [comment] 2021-02-23 19:58
Only Circle spells cast within a Create Contraption crash the game.

**Comment by Auxority** [comment] 2021-03-09 18:42
Can confirm this bug.

**Comment by DestroyerMCE** [comment] 2021-03-16 20:55
It is likely caused by the spell trying to move the contraption. the contraption doesn't like this, so it kills the game

**Comment by Auxority** [comment] 2021-03-17 11:55
> It is likely caused by the spell trying to move the contraption. the contraption doesn't like this, so it kills the game
The spell I used was a smelting spell though, it just looks for nearby smeltables.
It is still weird that this causes such behaviour.

**Comment by Kamefrede** [comment] 2021-03-19 14:10
I don't see anything in the log posted by the OP, could someone who experienced this bug post a log for both server and client?

**Comment by gjerm** [comment] 2021-03-19 20:54
I experience this bug specifically with any circle spell within a Create contraption. Sadly no client log but server log in this issue:

https://github.com/Creators-of-Create/Create/issues/1018

**Comment by archonxgames** [comment] 2021-03-22 09:37
Can confirm this issue still persists, I have a server that is currently experiencing this problem. I can send server log files if you guys need.

**Comment by Ouroel** [comment] 2021-03-22 09:50
Steps to replicate:

1). press F3 + B
2). make any create contraption
3). while inside, type /summon psi:spell_circle

**Comment by Ouroel** [comment] 2021-04-05 08:07
Fixed as of latest version

Closed

**Closed** 2021-04-09 08:28 UTC
Labels: bug
