### ISSUE TITLE
Psi energy bar does not render on certain window resolution

### ISSUE THREAD

**Issue by ProgrammedSoul** [Vazkii/Psi#352] opened 2017-07-07 07:38 UTC
Hi, quick problem report. I am having psi 1.0-42 installed on minecraft 1.10.2 and forge-12.18.3.2316. The psi energy bar is not rendering on certain resolution. Some people are reporting it won't render on auto UI scale config, some says with auto UI scale you need to set minecraft language to English in order to see energy bar. On my case, if you switch your minecraft language to some multi-char character language, like simplified Chinese, set UI scale to Auto, playing minecraft windowed on 1680x982 resolution (what F3 shown, this is maximized window on a 1920x1080 minitor, not sure why it is not 1920 x something), the energy bar will not render. It looks like some UI render problem, when the font is changed and the size of character changed, something will push the energy bar out of the screen. If I drag and change the window size, sometime I can see energy bar and sometime I could not. I do not have optifine, I had fpsPlus and foamFix but removing them does not help. Thank you in advance for your attention.

**Comment by Eusebius** [comment] 2019-09-03 08:33
Why has it been closed, is it because the bug is out-of-scope (caused by something outside the mod) or because it is fixed in some version? I'd really like to know since activating unicode fonts disables the energy bar for me as well. Thanks

**Comment by Kamefrede** [comment] 2019-09-03 16:45
This was closed because Vazkii did an issue cleanup since most issues were already fixed or didn't apply to the current version.

I'll be reopening it since it's still applicable I guess

**Comment by Kamefrede** [comment] 2020-03-29 23:41
Fixed on latest 1.15

**Closed by Kamefrede** 2020-03-29 23:41 UTC
