### ISSUE TITLE
Game crash after overflowing PSI to death

### ISSUE THREAD

**Issue by Haltfire30** [Vazkii/Psi#519] opened 2019-08-09 12:13 UTC
I'm playing on the Resonant Rise 5 pack through the AT-Launcher. I'm hosting a server through my PC (this gave me the log attached below). 

I occasionally will overflow my psi and immediately die, which is fine until I hit the "respawn" button. Once I hit the button, the entire game will crash and paste the log below in my server console. This has happened after overflowing with 2 different spells.

Here is the server log:
[Haltfire30ResonantRiseLog.txt](https://github.com/Vazkii/Psi/files/3486248/Haltfire30ResonantRiseLog.txt)

As well as the AT-Launcher crash log (which makes significantly less sense to me):
[crash-2019-08-09_07.52.54-client.txt](https://github.com/Vazkii/Psi/files/3486269/crash-2019-08-09_07.52.54-client.txt)

Let me know if you need any more info.

**Comment by MrMineO5** [comment] 2020-06-30 07:39
Is keepinventory enabled on the server?

**Comment by Kamefrede** [comment] 2020-10-19 09:47
Duplicate of #575, probably fixed in 1.16

**Closed by Kamefrede** 2020-10-19 09:47 UTC
Labels: duplicate, solved?
