### ISSUE TITLE
Chapter 18 Unable To Complete

### ISSUE THREAD

**Issue by XxChocoholicxX** [Vazkii/Psi#61] opened 2016-02-18 07:14 UTC
I just reached chapter 18 in my world with psi. In chapter 18 we have to use the wither effect. I tried it with my PsiSword and it withered the target but it didnt unlock chapter 19 for me. I tried with the same spell Direwolf used and it registered for him but not for me.

**Comment by GTMelo** [comment] 2016-02-18 07:43
I had a similar problem. I solved it by creating a simple spell that withers the caster and cast it two or three times.

**Comment by AlterAkima** [comment] 2016-02-18 10:38
The spell must be cast by a CAD, and does not need to be applied to the caster, the piece can just be on the spell.

**Comment by Vazkii** [comment] 2016-02-18 11:27
Dupe of #43

**Closed by Vazkii** 2016-02-18 11:27 UTC
