### ISSUE TITLE
A fatal error has occurred, this connection is terminated

### ISSUE THREAD

**Issue by Sunekaer** [Vazkii/Psi#458] opened 2018-12-27 00:02 UTC
Hey

Getting kick from server with message "A fatal error has occurred, this connection is terminated" when jumping
Log from server: https://gist.github.com/Sunekaer/e9b0b423c8382c8b4bd7520056ac56a7

**Comment by Sunekaer** [comment] 2018-12-27 00:09
forge-1.12.2-14.23.5.2796
Psi-r1.1-62

**Comment by yrsegal** [comment] 2018-12-27 00:10
Duplicate of Vazkii/AutoRegLib#23

**Closed** 2019-01-01 22:49 UTC
