### ISSUE TITLE
When Veinmining with a PsiMetal Pickaxe, with an explode spell, server crashes

### ISSUE THREAD

**Issue by kd8lvt** [Vazkii/Psi#19] opened 2016-02-12 22:54 UTC
[17:49:05] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockSto
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_51]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_51]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockStone$EnumType, values=[stone, gr
        at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137) ~[ama$a.class:?]
        at net.minecraft.block.BlockStone.func_176201_c(SourceFile:66) ~[ajy.class:?]
        at net.minecraft.block.Block.getHarvestTool(Block.java:2024) ~[afh.class:?]
        at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:133) ~[ForgeHooks.class:?]
        at net.minecraft.block.Block.canHarvestBlock(Block.java:1189) ~[afh.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180237_b(ItemInWorldManager.java:297) ~[lg.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180785_a(ItemInWorldManager.java:234) ~[lg.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:536) ~[lm.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:40) ~[ir.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:10) ~[ir.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_51]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_51]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
        ... 5 more
[17:49:13] [Server thread/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockSto
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_51]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_51]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [g.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:660) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) [ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockStone$EnumType, values=[stone, gr
        at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137) ~[ama$a.class:?]
        at net.minecraft.block.BlockStone.func_176201_c(SourceFile:66) ~[ajy.class:?]
        at net.minecraft.block.Block.getHarvestTool(Block.java:2024) ~[afh.class:?]
        at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:133) ~[ForgeHooks.class:?]
        at net.minecraft.block.Block.canHarvestBlock(Block.java:1189) ~[afh.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180237_b(ItemInWorldManager.java:297) ~[lg.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180785_a(ItemInWorldManager.java:234) ~[lg.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:536) ~[lm.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:40) ~[ir.class:?]
        at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:10) ~[ir.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fh$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_51]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_51]
        at net.minecraft.util.Util.func_181617_a(SourceFile:44) ~[g.class:?]
        ... 5 more
[17:49:14] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344) ~[ko.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockStone$EnumType, values=[stone, gr
        at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137) ~[ama$a.class:?]
        at net.minecraft.block.BlockStone.func_176201_c(SourceFile:66) ~[ajy.class:?]
        at net.minecraft.block.Block.getHarvestTool(Block.java:2024) ~[afh.class:?]
        at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:133) ~[ForgeHooks.class:?]
        at net.minecraft.block.Block.canHarvestBlock(Block.java:1189) ~[afh.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_180237_b(ItemInWorldManager.java:297) ~[lg.class:?]
        at net.minecraft.server.management.ItemInWorldManager.func_73075_a(ItemInWorldManager.java:104) ~[lg.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:217) ~[lf.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:1860) ~[adm.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:699) ~[le.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1829) ~[adm.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1661) ~[adm.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:544) ~[le.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701) ~[MinecraftServer.class:?]
        ... 4 more
[17:49:14] [Server thread/ERROR]: This crash report has been saved to: C:\Users\kd8lvt\Desktop\KdCraft Server\.\crash-reports\crash-2016-02-12_17.49.14-server.txt
[17:49:14] [Server thread/INFO]: Stopping server
[17:49:14] [Server thread/INFO]: Saving players
[17:49:14] [Server thread/INFO]: kd8lvt lost connection: TextComponent{text='Server closed', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic
[17:49:14] [Server thread/INFO]: kd8lvt left the game
[17:49:14] [Server thread/INFO]: Saving worlds
[17:49:14] [Server thread/INFO]: Saving chunks for level 'world'/Overworld
[17:49:15] [Server thread/INFO]: Saving chunks for level 'world'/Nether
[17:49:16] [Server thread/INFO]: Saving chunks for level 'world'/The Outer Lands
[17:49:16] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world 0
[17:49:21] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world -1
[17:49:21] [Server thread/INFO] [THAUMCRAFT]: Removing aura cache for world -42
[17:49:21] [Server thread/INFO] [FML]: Unloading dimension 0
[17:49:21] [Server thread/INFO] [FML]: Unloading dimension -1
[17:49:21] [Server thread/INFO] [FML]: Unloading dimension -42
[17:49:21] [Server thread/INFO] [FML]: Applying holder lookups
[17:49:21] [Server thread/INFO] [FML]: Holder lookups applied
[17:49:21] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by yrsegal** [comment] 2016-02-12 23:17
What mods?

**Comment by kd8lvt** [comment] 2016-02-12 23:23
modlist here: http://pastebin.com/TNGeEYHV
sorry, thats all that was in the crash file

**Comment by kd8lvt** [comment] 2016-02-12 23:23
If I had noticed they werent there I would have put them in hehe

**Comment by yrsegal** [comment] 2016-02-12 23:25
Could you upload the actual crash file? It has useful information.

**Comment by kd8lvt** [comment] 2016-02-12 23:28
[crash-2016-02-12_17.49.14-server.txt](https://github.com/Vazkii/Psi/files/128850/crash-2016-02-12_17.49.14-server.txt) Here you go, hope it helps!

**Comment by Vazkii** [comment] 2016-02-14 01:02
Dupe of #20, going with that one instead because it's less cluttered.

**Closed by Vazkii** 2016-02-14 01:02 UTC
