### ISSUE TITLE
Game completely crashed, said it was a casting issue

### ISSUE THREAD

**Issue by Benwager12** [Vazkii/Psi#527] opened 2019-09-17 16:40 UTC
Was playing a modpack and my game crashed as soon as I died (shot by blaze).
Because it was a casting error that included Psi, I thought I should post here, I was using a gun obviously alongside all the armor but the headgear.

The crash report is attached :)
[crash-2019-09-17_17.34.53-server.txt](https://github.com/Vazkii/Psi/files/3622519/crash-2019-09-17_17.34.53-server.txt)

**Comment by Kamefrede** [comment] 2020-10-19 09:47
Duplicate of #575, probably fixed in 1.16

**Closed by Kamefrede** 2020-10-19 09:47 UTC
Labels: duplicate, solved?
