### ISSUE TITLE
Motion bug with vehicles

### ISSUE THREAD

**Issue by SnazzGass** [Vazkii/Psi#489] opened 2019-03-08 06:14 UTC
This bug applies to all motion tricks:
-mass exodus
-add motion
-mass add motion

When a player is riding another entity, and is controlling that entity's motion (Ex: riding a pig AND holding carrot on a stick, or Riding a horse WITH a saddle), any motion tricks applied to that entity will reset its velocity to 0 rather than accelerating it.

**Comment by yrsegal** [comment] 2019-03-15 15:26
This was a duplicate of #490, apparently.

Not that I'm blaming you, they seemed different enough before I started working with the other issue.

Closed with https://github.com/Vazkii/Psi/commit/3ca0a1300e31945e6924e88b56995190c9200a54

**Closed by yrsegal** 2019-03-15 15:26 UTC
