### ISSUE TITLE
"Break Block" trick not breaking certain blocks in builds 38 and 39

### ISSUE THREAD

**Issue by Tacun** [Vazkii/Psi#258] opened 2016-10-02 14:04 UTC
I've noticed after updating from build 37 to 39 that certain blocks wont break anymore when using the "Break Block" and "Break Block Sequence" tricks. I went back and tested this with build 38 and have the same problem.  I noticed this in a mod pack but I reproduced it in an instance with only Forge, AutoRegLib, and PSI installed.

Note: I did have AutoRegLib installed when testing builds 38 and 39

A short list of blocks that no longer break(Likely incomplete): Bricks, Stone Bricks, Mossy Stone Bricks, Cracked Stone Bricks, Chiseled Stone Bricks, Furnaces, and Dispensers.

**Comment by Vazkii** [comment] 2016-10-04 21:57
Dupe of #253

**Closed by Vazkii** 2016-10-04 21:57 UTC
